spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchcontrol_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: batchcontrol_dev
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # 직접 SQL 실행했기 때문에 never로 설정
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

jwt:
  secret: batch-control-jwt-secret-key-256-bits-long-1234567890abcdefghijklmnopqrstuvwxyz
  token-validity-in-seconds: 86400 